Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (82,208693,null,'8.2  Aktualizace kmenových dat OPM',null,null,null,1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (83,208693,null,'8.3  Nový den',null,null,null,1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (84,208693,null,'8.4  Archivace OPM',null,null,null,1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (85,208693,null,'8.5  Tvorba stromové struktury',null,null,null,1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (86,208693,null,'8.6  Datová pumpa PXT (modul ESPO)',null,null,null,1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (87,208693,null,'8.7  Propojení OPM a SPO',null,null,null,1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (812,208693,null,'8.12  Detekce izolovaných OPM s charakterem odbìru BTS',null,null,null,1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (813,208693,null,'8.13  Generátor zpráv (modul ECMO)',null,null,null,1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (814,208693,null,'8.14  Import agregovaných profilù',null,null,null,1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (651,208693,null,'6.5.1  Asynchronní komunikace',null,null,null,1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (531,208693,null,'5.3.1  Uživatelská archivace OPM',null,null,null,1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (532,208693,null,'5.3.2  Uživatelské seskupení OPM',null,null,null,1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (533,208693,null,'5.3.3  Uživatelská zmìna režimu OPM s plánem',null,null,null,1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (534,208693,null,'5.3.4  Uživatelská historie spotøeby',null,null,null,1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (535,208693,null,'5.3.5  Uživatelský plán spotøeby',null,null,null,1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (88,208693,null,'8.8  Ztráta OPM v LDS s dopoètem (CR)',null,null,null,1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (89,208693,null,'8.9  Øízení importu profilù mìøení',null,null,null,1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (810,208693,null,'8.10  Øízení výpoètu agregace TS',null,null,null,1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (811,208693,null,'8.11  Kontrola modelu SPO',null,null,null,1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (821,49745,'K','Zpracována zpráva kmenových dat (353)','82AI',82,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (831,49745,'S','Zahájen pøechod na nový den','83AI',83,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (832,49745,'O','Pøechod OPM do období v dodávce','83BI',83,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (833,49745,'O','Pøechod OPM do období po skonèení dodávky','83CI',83,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (834,49745,'O','Zrušeno seskupení ztraceného OPM','83DW',83,'W',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (835,49745,'O','Zrušen režim plánované OPM ztraceného OPM','83EI',83,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (855,49745,'O','Zpìtný posun platnosti','85EW',85,'W',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (836,49745,'S','Dokonèen pøechod na nový den','83FI',83,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (837,49745,'S','Pøechod na nový den skonèil chybou','83GE',83,'E',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (838,49745,'P','Dokonèen pøepoèet (nový den)','83HI',83,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (839,49745,'O','OPM bez plánu spotøeby','83IW',83,'W',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (840,49745,'O','Znovuzískané OPM bez dostateèné historie mìøení','83JW',83,'W',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (841,49745,'S','Zahájena archivace OPM','84AI',84,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (842,49745,'O','OPM zaøazené do archivu','84BI',84,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (843,49745,'O','Zrušeno seskupení archivovaného OPM','84CW',84,'W',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (844,49745,'O','Zrušen režim plánované OPM archivovaného OPM','84DI',84,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (845,49745,'O','OPM vyjmuté z archivu','84EI',84,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (846,49745,'S','Dokonèena archivace OPM','84FI',84,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (847,49745,'S','Zpracování archivace OPM skonèilo chybou','84GE',84,'E',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (851,49745,'S','Zahájena aktualizace stromové struktury','85AI',85,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (852,49745,'O','Získané OPM typu A/B','85CI',85,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (853,49745,'O','Znovuzískané OPM typu A/B','85DI',85,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (854,49745,'S','Dokonèena aktualizace stromové struktury','85EI',85,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (8111,208693,null,'8.11.1  Kontrola plnìní plánu (PXT)',null,null,null,1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (8112,208693,null,'8.11.2  Porovnání technické predikce spotøeby s plánem spotøeby (PXT)',null,null,null,1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (861,49749,'S','Spuštìno zpracování datové pumpy PXT','86AI',86,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (862,49749,'X','Nové SPO','86BI',86,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (863,49749,'X','Pøiøazeno OPM k SPO','86DI',86,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (864,49749,'X','Smazané OPM v SPO','86EI',86,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (865,49749,'X','Zmìna stavu SPO','86FW',86,'W',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (866,49749,'X','Úspìšné stažení agr. plánu SPO','86GI',86,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (867,49749,'X','Úspìšné stažení plánu OPM (SPO)','86HI',86,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (868,49749,'X','Chyba stažení plánu OPM','86IW',86,'W',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (869,49749,'S','Dokonèeno zpracování datové pumpy PXT','86JI',86,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (870,49749,'S','Zpracování datové pumpy PXT skonèilo chybou','86JE',86,'E',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (871,49749,'S','Spuštìno propojení evidence OTE a PXT','87AI',87,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (872,49749,'O','Neexistuje aktivní SPO pro získané/znovuzískané OPM','87BW',87,'W',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (873,49749,'O','Neexistuje plán OPM v aktivní SPO','87CW',87,'W',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (874,49749,'S','Dokonèeno propojení evidence OTE a PXT','87DI',87,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (875,49749,'S','Vytvoøení propojení evidence OTE a PXT skonèilo chybou','87DE',87,'E',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (881,49749,'K','Zpracována zpráva ztráty OPM v LDS s dopoètem','88AI',88,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (882,49749,'O','Zpracována informace o ztraceném OPM v LDS s dopoètem','88BW',88,'W',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (883,523737,'O','Pøi zpracování ztraceného OPM v LDS s dopoètem došlo k chybì (OPM již existuje v DB)','88BE',88,'E',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (891,49749,'K','Zpracováno první dnešní mìøení V99','89DI',89,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (892,49749,'K','Zpracováno první dnešní mìøení V0','89AI',89,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (893,49749,'K','Zpracováno první dnešní mìøení V1','89BI',89,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (894,49749,'K','Zpracováno první dnešní mìøení V2','89CI',89,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (895,49749,'S','Zahájení druhé fáze importu profilù mìøení','89HI',89,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (896,49749,'S','Dokonèena druhá fáze importu profilù mìøení','89II',89,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (897,49749,'S','V rámci druhé fáze importu profilù mìøení došlo k chybì','89IE',89,'E',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (898,49749,'S','V rámci zpracované dávky zpráv profilù se nepodaøilo dohledat nìkteré OPM v DB','89KW',89,'W',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (8101,49749,'R','Zahájení pøepoètu agregace RDS/LDS','810AI',810,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (8102,49749,'R','Dokonèení pøepoètu agregace RDS/LDS','810BI',810,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (8103,49749,'P','Zahájení pøepoètu celkové agregace','810CI',810,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (8104,49749,'P','Dokonèení pøepoètu celkové agregace','810DI',810,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (81111,49749,'O','Plánované OPM neplní plán a pøechází do režimu [T]','8111AI',8111,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (81121,49749,'O','Pro znovuzískané OPM preferujeme technickou predikci spotøeby (pøechod do režimu [T])','8112BI',8112,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (81122,49749,'O','Pro znovuzískané OPM preferujeme plán spotøeby (pøechod do režimu [P])','8112CI',8112,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (8121,49749,'S','Spuštìní procesu detekce OPM s charakterem odbìru BTS','812AI',812,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (8122,49749,'O','Detekováno OPM s charakterem odbìru BTS','812BI',812,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (8123,49749,'S','Dokonèen proces detekce OPM s charakterem odbìru BTS','812CI',812,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (8124,49749,'S','Proces detekce OPM s charakterem odbìru BTS skonèil chybou','812CE',812,'E',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (8131,49749,'K','Vyžádána aktualizace kmenových dat OPM','813AI',813,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (8132,49749,'K','Vyžádány agregované profily SZ','813BI',813,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (8133,49749,'K','Od okamžiku vygenerování dotazu D uplynul timeout T','813CE',813,'E',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (6511,49749,'K','Zpracována zpráva RESPONSE s chybou zpracování dotazu (@message-code, //Reference/@id, obsah zprávy dle xpath)','651AE',651,'E',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (8141,49749,'K','Zpracována vyžádaná zpráva agregované profily èlenìní SZ (643)','814AI',814,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (8142,49749,'K','Pøi importu agregovaných profilù ve èlenìní dle SZ (643) došlo k chybì','814BE',814,'E',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (8143,49749,'K','Zpracována vyžádaná zpráva agregované profily èlenìní SZ a RDS/LDS (653)','814CI',814,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (8144,49749,'K','Pøi importu agregovaných profilù ve èlenìní dle SZ a RDS/LDS (653) došlo k chybì','814DW',814,'W',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (8145,49749,'S','V rámci zpracované dávky zpráv profilù se nepodaøilo dohledat objekt dopoètového nebo agregaèního OPM v DB','814EW',814,'W',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (5312,49749,'O','Uživatelská zmìna stavu archivace','531AI',531,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (5321,49749,'O','Uživatelská zmìna stavu seskupení [S]','532AI',532,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (5331,49749,'O','Uživatelská zmìna režimu [T]/[P]','533AI',533,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (5341,49749,'O','Uživatelská zmìna historie spotøeby','534AI',534,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (5351,49749,'O','Uživatelská zmìna plánu spotøeby','535AI',535,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (8401,452034,'O','Zpracována informace o ztraceném OPM v LDS s dopoètem','83KW',83,'W',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (822,523723,'K','Pøi zpracování zprávy kmenových dat (353) došlo k chybì','82FE',82,'I',1);
Insert into TTS_AUDITCODES (ID,EE_TRANS_ID,CATEGORY,DESCRIPTION,KEY,PARENTID,STATE,SYS_VER) values (884,523740,'K','Pøi zpracování zprávy kmenových dat (X178) došlo k chybì','88DE',88,'E',1);

commit;